[package]
name = "EVA-Checklist"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Archie Webster <https://github.com/artomweb>"]
license = "MIT"
description = "A template for creating NASA Gemini (1966) style checklists."
repository = "https://github.com/artomweb/EVA-Checklist.git"
keywords = ["NASA", "aviation", "checklist"]
categories = ["utility"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"